---
- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: retrieve vpc information
      amazon.aws.ec2_vpc_net_info:
        region: "{{ ec2_region | default('ap-southeast-2') }}"
      register: vpc_info

    - name: print vpc info to terminal
      ansible.builtin.debug:
        msg: "{{ vpc_info }}"
